language: php

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3

before_script:

before_install:
    - travis_retry composer self-update

install: composer update --prefer-source --no-interaction

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpunit
